---
- name: include check_mandatory_vars.yml
  include: check_mandatory_vars.yml

- name: include deploy_monitors.yml
  include: deploy_monitors.yml
  when: not containerized_deployment

- name: include start_monitor.yml
  include: start_monitor.yml
  when: not containerized_deployment

- name: include ceph_keys.yml
  include: ceph_keys.yml
  when: not containerized_deployment
  # this avoids the bug mentioned here: https://github.com/ansible/ansible/issues/18206
  static: no

- name: include secure_cluster.yml
  include: secure_cluster.yml
  when:
    - secure_cluster
    - not containerized_deployment

- name: include set_osd_pool_default_pg_num.yml
  include: set_osd_pool_default_pg_num.yml
