---

- name: include pre_requisite.yml
  include: pre_requisite.yml
  when:
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: include d42setup/main.yml
  include: d42setup/main.yml
  when:
    - rgw_zone is defined
    - ceph_release_num[ceph_release] >= ceph_release_num.jewel
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False
