- include_vars: group_vars/prod-d42sa.yml

- name: define cmds
  set_fact: cmds

- name: Generate Pool commands
  local_action: command python ./scripts/pgcalc.py {{ item.0 }} {{ item.1 }} {{ item.2 }} {{ item.3 }} {{ item.4 }} {{ item.5 }} {{ item.6  }} {{ item.7 }}
  msg: "Element:: {{ pool_cmd.stdout }}"
  changed_when: False
  with_together:
  - "{{ osdNum }}"
  - "{{ size }}"
  - "{{ targetPGs }}"
  - "{{ percData }}"
  - "{{ pools }}"
  - "{{ poolRoot }}"
  - "{{ poolType }}"
  - "{{ min_size }}"
  register: pool_cmd

- name: append cmds to list
  set_fact:
    cmds:
          "{% for i in pool_cmd.results %}/{{i.stdout}}{% endfor %}"

- name: xyz
  set_fact: acommand="{{cmds.split('/')}}"

- name: run commands
  become: true
  msg: "{{item}}"
  shell: "{{item}}"
  with_items: "{{acommand}}"
  when: 'item not in ""'

